[theme]
# Primary accent color for interactive elements.
primaryColor="#b1d4f0"
# Background color for the main content area.  #e9eef2
backgroundColor="#FF4B4B"
# Background color for sidebar and most interactive widgets.
secondaryBackgroundColor="#b1d4f0"
# Color used for almost all text.
textColor="#000000"